import{a as l,S as u,i}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d="https://pixabay.com/api/",f="52807381-7a65b057c23058f47f8cb5df4";async function y(a){try{return(await l.get(d,{params:{key:f,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(r){throw console.error("Помилка запиту до Pixabay:",r),r}}const m=new u(".gallery a",{captionsData:"alt",captionDelay:250});function p(a){const r=document.querySelector(".gallery"),n=a.map(o=>`
    <li>
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        <p>Likes: ${o.likes} | Views: ${o.views} | Comments: ${o.comments} | Downloads: ${o.downloads}</p>
      </a>
    </li>
  `).join("");r.insertAdjacentHTML("beforeend",n),m.refresh()}function h(){document.querySelector(".gallery").innerHTML=""}function g(){document.querySelector(".loader").classList.remove("hidden")}function L(){document.querySelector(".loader").classList.add("hidden")}const c=document.querySelector(".form");c.addEventListener("submit",async a=>{a.preventDefault();const r=c.elements["search-text"].value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search query"});return}h(),g();try{const n=await y(r);n.hits.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):p(n.hits)}catch{i.error({title:"Error",message:"Something went wrong. Please try again."})}finally{L()}});
//# sourceMappingURL=index.js.map
